
services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: karkipy
      POSTGRES_PASSWORD: lpbmis@1234
      POSTGRES_DB: lpbmis
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: